/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseWidgetDraggable: typeof import('./src/components/Draggable/BaseWidgetDraggable.vue')['default']
    BookmarkConfiguration: typeof import('./src/components/Bookmark/BookmarkConfiguration.vue')['default']
    BookmarkConfigurationToolsAdd: typeof import('./src/components/Bookmark/BookmarkConfigurationToolsAdd.vue')['default']
    Bookmarks: typeof import('./src/components/Bookmark/Bookmarks.vue')['default']
    Clock: typeof import('./src/components/Clock/Clock.vue')['default']
    ClockDraggable: typeof import('./src/components/Clock/ClockDraggable.vue')['default']
    IconBookmarks: typeof import('./src/components/icons/IconBookmarks.vue')['default']
    IconClassMate: typeof import('./src/components/icons/IconClassMate.vue')['default']
    IconClock: typeof import('./src/components/icons/IconClock.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconLessons: typeof import('./src/components/icons/IconLessons.vue')['default']
    IconNotes: typeof import('./src/components/icons/IconNotes.vue')['default']
    IconPlaylist: typeof import('./src/components/icons/IconPlaylist.vue')['default']
    IconSettings: typeof import('./src/components/icons/IconSettings.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTimer: typeof import('./src/components/icons/IconTimer.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Label: typeof import('./src/components/Label/Label.vue')['default']
    Lessons: typeof import('./src/components/Lesson/Lessons.vue')['default']
    LessonsConfiguration: typeof import('./src/components/Lesson/LessonsConfiguration.vue')['default']
    PersonalEditor: typeof import('./src/components/Editor/PersonalEditor.vue')['default']
    Playlist: typeof import('./src/components/Playlist/Playlist.vue')['default']
    PlaylistConfiguration: typeof import('./src/components/Playlist/PlaylistConfiguration.vue')['default']
    RoleSelect: typeof import('./src/components/Role/RoleSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stopwatch: typeof import('./src/components/Timer/Stopwatch.vue')['default']
    StyleConfiguration: typeof import('./src/components/StyleConfiguration/StyleConfiguration.vue')['default']
    SwitchableTimer: typeof import('./src/components/Timer/SwitchableTimer.vue')['default']
    Timer: typeof import('./src/components/Timer/Timer.vue')['default']
  }
}
