/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseWidgetDraggable: typeof import('./src/components/Draggable/BaseWidgetDraggable.vue')['default']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BCollapse: typeof import('bootstrap-vue-next/components/BCollapse')['BCollapse']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckbox']
    BFormFloatingLabel: typeof import('bootstrap-vue-next/components/BForm')['BFormFloatingLabel']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BookmarkConfiguration: typeof import('./src/components/Bookmark/BookmarkConfiguration.vue')['default']
    BookmarkConfigurationToolsAdd: typeof import('./src/components/Bookmark/BookmarkConfigurationToolsAdd.vue')['default']
    Bookmarks: typeof import('./src/components/Bookmark/Bookmarks.vue')['default']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BTab: typeof import('bootstrap-vue-next/components/BTabs')['BTab']
    BTableSimple: typeof import('bootstrap-vue-next/components/BTable')['BTableSimple']
    BTabs: typeof import('bootstrap-vue-next/components/BTabs')['BTabs']
    BTbody: typeof import('bootstrap-vue-next/components/BTable')['BTbody']
    BTd: typeof import('bootstrap-vue-next/components/BTable')['BTd']
    BTh: typeof import('bootstrap-vue-next/components/BTable')['BTh']
    BThead: typeof import('bootstrap-vue-next/components/BTable')['BThead']
    BTr: typeof import('bootstrap-vue-next/components/BTable')['BTr']
    Clock: typeof import('./src/components/Clock/Clock.vue')['default']
    CustomDraggable: typeof import('./src/components/Draggable/CustomDraggable.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Label: typeof import('./src/components/Label/Label.vue')['default']
    Lessons: typeof import('./src/components/Lesson/Lessons.vue')['default']
    PersonalEditor: typeof import('./src/components/Editor/PersonalEditor.vue')['default']
    Playlist: typeof import('./src/components/Playlist/Playlist.vue')['default']
    RoleSelect: typeof import('./src/components/Role/RoleSelect.vue')['default']
    Stopwatch: typeof import('./src/components/Timer/Stopwatch.vue')['default']
    StyleConfiguration: typeof import('./src/components/StyleConfiguration/StyleConfiguration.vue')['default']
    SwitchableTimer: typeof import('./src/components/Timer/SwitchableTimer.vue')['default']
    Timer: typeof import('./src/components/Timer/Timer.vue')['default']
    WidgetWrapper: typeof import('./src/components/Widget/WidgetWrapper.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBTooltip: typeof import('bootstrap-vue-next/directives/BTooltip')['vBTooltip']
  }
}
