name: Export issues
on:
  workflow_dispatch:
jobs:
  deploy:
    name: Export issues to S3
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Update to the latest version to use Node 16

    - name: Setup gh CLI
      run: |
        curl -sSL https://github.com/cli/cli/releases/download/v2.3.0/gh_x86_64_linux.tar.gz | tar -xz
        sudo cp gh_x86_64_linux/bin/gh /usr/local/bin/gh

    - name: Print Runner Architecture
      run: echo $RUNNER_ARCH

    - name: Export issues
      uses: niteoweb/export-issues-action@v2
      with:
        repo: ${{ github.repository }}
        org: ${{ github.repository_owner }}

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: issues
        path: "issues/*.md"
