name: Export Issues

on:
  workflow_dispatch:

jobs:
  export_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup gh CLI
        run: |
          curl -sSL https://github.com/cli/cli/releases/download/v2.3.0/gh_2.3.0_linux_amd64.tar.gz | tar -xz
          sudo cp gh_2.3.0_linux_amd64/bin/gh /usr/local/bin/gh

      - name: Export Issues
        uses: teamniteo/export-issues-action@e065c7486951d38b0161091f191281001c9c6d23
        with:
          repo: ClassMate
          org: LBTU-IT-M24
